[package]
name = "plist-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = "1.3"
env_logger = "0.9"
log = "0.4"
percent-encoding = "2.2"
encoding_rs = "0.8"
